// lib/alerts-mock-data.ts

import {
  Alert,
  AlertSeverity,
  AlertState,
  TriggeredEvent,
  AlertMetrics,
  WatchedTechnology,
  AlertTemplate,
  NotificationPreference,
  MatchedDocument,
  TechUpdate,
  AlertPreviewResult,
} from '@/types/alerts';

export const mockAlerts: Alert[] = [
  {
    id: 'alert-1',
    name: 'Quantum Computing Breakthroughs',
    description: 'Monitor major developments in quantum computing technology',
    severity: 'critical',
    state: 'active',
    triggerType: 'query',
    conditions: [
      {
        id: 'cond-1',
        field: 'domain',
        operator: 'equals',
        value: 'Quantum Computing',
      },
      {
        id: 'cond-2',
        field: 'trl',
        operator: 'greater_than',
        value: 7,
        logic: 'AND',
      },
    ],
    frequency: 'real-time',
    deliveryChannels: [
      {
        channel: 'in-app',
        enabled: true,
        config: {},
      },
      {
        channel: 'email',
        enabled: true,
        config: {
          to: ['team@intelforge.com', 'alerts@company.com'],
          subject: '[CRITICAL] Quantum Computing Alert',
          template: 'critical-alert',
        },
      },
      {
        channel: 'slack',
        enabled: true,
        config: {
          webhookUrl: 'https://hooks.slack.com/services/xxx',
          slackChannel: '#tech-alerts',
        },
      },
    ],
    dedupRules: {
      enabled: true,
      window: 60,
      field: 'title',
    },
    throttle: {
      enabled: true,
      suppressionWindow: 30,
      maxEventsPerWindow: 5,
    },
    teamSubscriptions: ['user-1', 'user-2', 'team-research'],
    createdBy: 'user-1',
    createdAt: '2024-10-15T10:00:00Z',
    updatedAt: '2024-11-18T14:30:00Z',
    lastTriggered: '2024-11-20T08:45:00Z',
    triggerCount: 24,
    estimatedNoise: 15,
  },
  {
    id: 'alert-2',
    name: 'AI Safety Research Publications',
    description: 'Track new research papers on AI safety and alignment',
    severity: 'high',
    state: 'active',
    triggerType: 'signal',
    conditions: [
      {
        id: 'cond-3',
        field: 'signal_type',
        operator: 'equals',
        value: 'research_publication',
      },
      {
        id: 'cond-4',
        field: 'keywords',
        operator: 'contains',
        value: 'AI safety',
        logic: 'AND',
      },
    ],
    frequency: 'daily',
    deliveryChannels: [
      {
        channel: 'in-app',
        enabled: true,
        config: {},
      },
      {
        channel: 'email',
        enabled: true,
        config: {
          to: ['research@intelforge.com'],
          subject: 'Daily AI Safety Research Digest',
          template: 'daily-digest',
        },
      },
    ],
    dedupRules: {
      enabled: true,
      window: 1440, // 24 hours
      field: 'doi',
    },
    throttle: {
      enabled: false,
      suppressionWindow: 0,
      maxEventsPerWindow: 0,
    },
    teamSubscriptions: ['team-ai-research'],
    createdBy: 'user-3',
    createdAt: '2024-09-20T09:15:00Z',
    updatedAt: '2024-11-10T11:20:00Z',
    lastTriggered: '2024-11-19T23:00:00Z',
    triggerCount: 42,
    estimatedNoise: 8,
  },
  {
    id: 'alert-3',
    name: 'Solid-State Battery Funding',
    description: 'Alert on major investments in solid-state battery technology',
    severity: 'medium',
    state: 'active',
    triggerType: 'threshold',
    conditions: [
      {
        id: 'cond-5',
        field: 'technology',
        operator: 'contains',
        value: 'solid-state battery',
      },
      {
        id: 'cond-6',
        field: 'funding_amount',
        operator: 'greater_than',
        value: 10000000,
        logic: 'AND',
      },
    ],
    frequency: 'real-time',
    deliveryChannels: [
      {
        channel: 'in-app',
        enabled: true,
        config: {},
      },
      {
        channel: 'webhook',
        enabled: true,
        config: {
          endpoint: 'https://api.company.com/webhooks/funding-alerts',
          headers: {
            'Content-Type': 'application/json',
          },
          authToken: 'Bearer xxx-token',
        },
      },
    ],
    dedupRules: {
      enabled: true,
      window: 120,
      field: 'organization',
    },
    throttle: {
      enabled: true,
      suppressionWindow: 60,
      maxEventsPerWindow: 3,
    },
    teamSubscriptions: ['team-investment'],
    createdBy: 'user-2',
    createdAt: '2024-11-01T14:00:00Z',
    updatedAt: '2024-11-15T16:45:00Z',
    lastTriggered: '2024-11-18T10:20:00Z',
    triggerCount: 7,
    estimatedNoise: 22,
  },
  {
    id: 'alert-4',
    name: 'CRISPR Patent Filings',
    description: 'Monitor new patent applications in CRISPR gene editing',
    severity: 'high',
    state: 'muted',
    triggerType: 'entity',
    conditions: [
      {
        id: 'cond-7',
        field: 'entity_type',
        operator: 'equals',
        value: 'patent',
      },
      {
        id: 'cond-8',
        field: 'technology_area',
        operator: 'contains',
        value: 'CRISPR',
        logic: 'AND',
      },
    ],
    frequency: 'weekly',
    deliveryChannels: [
      {
        channel: 'in-app',
        enabled: true,
        config: {},
      },
      {
        channel: 'email',
        enabled: true,
        config: {
          to: ['legal@intelforge.com'],
          subject: 'Weekly CRISPR Patent Report',
          template: 'weekly-report',
        },
      },
    ],
    dedupRules: {
      enabled: true,
      window: 10080, // 1 week
      field: 'patent_number',
    },
    throttle: {
      enabled: false,
      suppressionWindow: 0,
      maxEventsPerWindow: 0,
    },
    teamSubscriptions: ['team-legal'],
    createdBy: 'user-4',
    createdAt: '2024-08-10T08:30:00Z',
    updatedAt: '2024-11-17T12:00:00Z',
    lastTriggered: '2024-11-11T09:00:00Z',
    triggerCount: 15,
    estimatedNoise: 12,
  },
  {
    id: 'alert-5',
    name: 'Nuclear Fusion Progress',
    description: 'Track significant milestones in nuclear fusion development',
    severity: 'critical',
    state: 'active',
    triggerType: 'query',
    conditions: [
      {
        id: 'cond-9',
        field: 'keywords',
        operator: 'contains',
        value: 'nuclear fusion',
      },
      {
        id: 'cond-10',
        field: 'signal_strength',
        operator: 'greater_than',
        value: 0.8,
        logic: 'AND',
      },
    ],
    frequency: 'hourly',
    deliveryChannels: [
      {
        channel: 'in-app',
        enabled: true,
        config: {},
      },
      {
        channel: 'slack',
        enabled: true,
        config: {
          webhookUrl: 'https://hooks.slack.com/services/yyy',
          slackChannel: '#energy-tech',
        },
      },
    ],
    dedupRules: {
      enabled: true,
      window: 180,
      field: 'content_hash',
    },
    throttle: {
      enabled: true,
      suppressionWindow: 120,
      maxEventsPerWindow: 2,
    },
    teamSubscriptions: ['user-5', 'team-energy'],
    createdBy: 'user-5',
    createdAt: '2024-10-05T11:45:00Z',
    updatedAt: '2024-11-19T15:30:00Z',
    lastTriggered: '2024-11-20T06:00:00Z',
    triggerCount: 31,
    estimatedNoise: 18,
  },
  {
    id: 'alert-6',
    name: 'Competitor Analysis - TechCorp',
    description: 'Monitor competitor activities and announcements',
    severity: 'medium',
    state: 'active',
    triggerType: 'entity',
    conditions: [
      {
        id: 'cond-11',
        field: 'organization',
        operator: 'equals',
        value: 'TechCorp',
      },
    ],
    frequency: 'daily',
    deliveryChannels: [
      {
        channel: 'in-app',
        enabled: true,
        config: {},
      },
      {
        channel: 'email',
        enabled: true,
        config: {
          to: ['strategy@intelforge.com'],
          subject: 'TechCorp Daily Digest',
          template: 'competitor-digest',
        },
      },
    ],
    dedupRules: {
      enabled: true,
      window: 720,
      field: 'url',
    },
    throttle: {
      enabled: false,
      suppressionWindow: 0,
      maxEventsPerWindow: 0,
    },
    teamSubscriptions: ['team-strategy'],
    createdBy: 'user-1',
    createdAt: '2024-09-15T10:00:00Z',
    updatedAt: '2024-11-12T09:30:00Z',
    lastTriggered: '2024-11-19T22:00:00Z',
    triggerCount: 58,
    estimatedNoise: 25,
  },
];

export const mockTriggeredEvents: TriggeredEvent[] = [
  {
    id: 'event-1',
    alertId: 'alert-1',
    alertName: 'Quantum Computing Breakthroughs',
    severity: 'critical',
    triggeredAt: '2024-11-20T08:45:00Z',
    matchedDocuments: [
      {
        id: 'doc-1',
        title: 'IBM Announces 1000-Qubit Quantum Processor',
        source: 'IBM Research',
        url: 'https://research.ibm.com/quantum-1000',
        excerpt: 'IBM has successfully demonstrated a 1000-qubit quantum processor with unprecedented error correction capabilities...',
        matchScore: 0.95,
        publishedAt: '2024-11-20T08:00:00Z',
        metadata: {
          domain: 'Quantum Computing',
          trl: 8,
          country: 'United States',
        },
      },
    ],
    evidenceSnapshot: {
      query: 'domain:Quantum Computing AND trl:>7',
      conditions: [
        {
          id: 'cond-1',
          field: 'domain',
          operator: 'equals',
          value: 'Quantum Computing',
        },
        {
          id: 'cond-2',
          field: 'trl',
          operator: 'greater_than',
          value: 7,
          logic: 'AND',
        },
      ],
      totalMatches: 1,
      sampleDocuments: [
        {
          id: 'doc-1',
          title: 'IBM Announces 1000-Qubit Quantum Processor',
          source: 'IBM Research',
          url: 'https://research.ibm.com/quantum-1000',
          excerpt: 'IBM has successfully demonstrated a 1000-qubit quantum processor...',
          matchScore: 0.95,
          publishedAt: '2024-11-20T08:00:00Z',
          metadata: {},
        },
      ],
      capturedAt: '2024-11-20T08:45:00Z',
    },
    actionsPerformed: [
      {
        id: 'action-1',
        action: 'delivered',
        channel: 'in-app',
        timestamp: '2024-11-20T08:45:10Z',
        details: 'Notification delivered to 3 users',
        success: true,
      },
      {
        id: 'action-2',
        action: 'delivered',
        channel: 'email',
        timestamp: '2024-11-20T08:45:15Z',
        details: 'Email sent to team@intelforge.com',
        success: true,
      },
      {
        id: 'action-3',
        action: 'delivered',
        channel: 'slack',
        timestamp: '2024-11-20T08:45:20Z',
        details: 'Message posted to #tech-alerts',
        success: true,
      },
    ],
    deliveryStatus: [
      {
        channel: 'in-app',
        status: 'delivered',
        timestamp: '2024-11-20T08:45:10Z',
        retryCount: 0,
      },
      {
        channel: 'email',
        status: 'delivered',
        timestamp: '2024-11-20T08:45:15Z',
        retryCount: 0,
      },
      {
        channel: 'slack',
        status: 'delivered',
        timestamp: '2024-11-20T08:45:20Z',
        retryCount: 0,
      },
    ],
  },
  {
    id: 'event-2',
    alertId: 'alert-3',
    alertName: 'Solid-State Battery Funding',
    severity: 'medium',
    triggeredAt: '2024-11-18T10:20:00Z',
    matchedDocuments: [
      {
        id: 'doc-2',
        title: 'QuantumScape Secures $150M Series E Funding',
        source: 'TechCrunch',
        url: 'https://techcrunch.com/quantumscape-funding',
        excerpt: 'Solid-state battery manufacturer QuantumScape announced today it has raised $150 million in Series E funding...',
        matchScore: 0.88,
        publishedAt: '2024-11-18T09:30:00Z',
        metadata: {
          funding_amount: 150000000,
          organization: 'QuantumScape',
        },
      },
    ],
    evidenceSnapshot: {
      query: 'technology:solid-state battery AND funding:>10M',
      conditions: [
        {
          id: 'cond-5',
          field: 'technology',
          operator: 'contains',
          value: 'solid-state battery',
        },
        {
          id: 'cond-6',
          field: 'funding_amount',
          operator: 'greater_than',
          value: 10000000,
          logic: 'AND',
        },
      ],
      totalMatches: 1,
      sampleDocuments: [
        {
          id: 'doc-2',
          title: 'QuantumScape Secures $150M Series E Funding',
          source: 'TechCrunch',
          url: 'https://techcrunch.com/quantumscape-funding',
          excerpt: 'Solid-state battery manufacturer QuantumScape...',
          matchScore: 0.88,
          publishedAt: '2024-11-18T09:30:00Z',
          metadata: {},
        },
      ],
      capturedAt: '2024-11-18T10:20:00Z',
    },
    actionsPerformed: [
      {
        id: 'action-4',
        action: 'delivered',
        channel: 'in-app',
        timestamp: '2024-11-18T10:20:05Z',
        details: 'Notification delivered',
        success: true,
      },
      {
        id: 'action-5',
        action: 'delivered',
        channel: 'webhook',
        timestamp: '2024-11-18T10:20:10Z',
        details: 'Webhook POST successful',
        success: true,
      },
    ],
    deliveryStatus: [
      {
        channel: 'in-app',
        status: 'delivered',
        timestamp: '2024-11-18T10:20:05Z',
        retryCount: 0,
      },
      {
        channel: 'webhook',
        status: 'delivered',
        timestamp: '2024-11-18T10:20:10Z',
        retryCount: 0,
      },
    ],
  },
  {
    id: 'event-3',
    alertId: 'alert-5',
    alertName: 'Nuclear Fusion Progress',
    severity: 'critical',
    triggeredAt: '2024-11-20T06:00:00Z',
    matchedDocuments: [
      {
        id: 'doc-3',
        title: 'NIF Achieves Net Energy Gain in Fusion Reaction',
        source: 'Nature',
        url: 'https://nature.com/fusion-net-gain',
        excerpt: 'The National Ignition Facility has achieved a historic milestone with net energy gain from fusion reaction...',
        matchScore: 0.92,
        publishedAt: '2024-11-20T05:00:00Z',
        metadata: {
          signal_strength: 0.89,
          impact_score: 9.5,
        },
      },
    ],
    evidenceSnapshot: {
      query: 'keywords:nuclear fusion AND signal_strength:>0.8',
      conditions: [
        {
          id: 'cond-9',
          field: 'keywords',
          operator: 'contains',
          value: 'nuclear fusion',
        },
        {
          id: 'cond-10',
          field: 'signal_strength',
          operator: 'greater_than',
          value: 0.8,
          logic: 'AND',
        },
      ],
      totalMatches: 1,
      sampleDocuments: [
        {
          id: 'doc-3',
          title: 'NIF Achieves Net Energy Gain in Fusion Reaction',
          source: 'Nature',
          url: 'https://nature.com/fusion-net-gain',
          excerpt: 'The National Ignition Facility has achieved...',
          matchScore: 0.92,
          publishedAt: '2024-11-20T05:00:00Z',
          metadata: {},
        },
      ],
      capturedAt: '2024-11-20T06:00:00Z',
    },
    actionsPerformed: [
      {
        id: 'action-6',
        action: 'delivered',
        channel: 'in-app',
        timestamp: '2024-11-20T06:00:08Z',
        details: 'Notification delivered to team',
        success: true,
      },
      {
        id: 'action-7',
        action: 'delivered',
        channel: 'slack',
        timestamp: '2024-11-20T06:00:12Z',
        details: 'Message posted to #energy-tech',
        success: true,
      },
    ],
    deliveryStatus: [
      {
        channel: 'in-app',
        status: 'delivered',
        timestamp: '2024-11-20T06:00:08Z',
        retryCount: 0,
      },
      {
        channel: 'slack',
        status: 'delivered',
        timestamp: '2024-11-20T06:00:12Z',
        retryCount: 0,
      },
    ],
  },
  {
    id: 'event-4',
    alertId: 'alert-2',
    alertName: 'AI Safety Research Publications',
    severity: 'high',
    triggeredAt: '2024-11-19T23:00:00Z',
    matchedDocuments: [
      {
        id: 'doc-4',
        title: 'Constitutional AI: Harmlessness from AI Feedback',
        source: 'arXiv',
        url: 'https://arxiv.org/abs/2212.xxxxx',
        excerpt: 'We introduce a method for training AI systems to be helpful, harmless, and honest using constitutional principles...',
        matchScore: 0.91,
        publishedAt: '2024-11-19T18:00:00Z',
        metadata: {
          signal_type: 'research_publication',
          citations: 124,
        },
      },
      {
        id: 'doc-5',
        title: 'Scalable Oversight for Large Language Models',
        source: 'OpenAI Research',
        url: 'https://openai.com/research/scalable-oversight',
        excerpt: 'This paper explores methods for providing effective oversight of increasingly capable AI systems...',
        matchScore: 0.87,
        publishedAt: '2024-11-19T20:30:00Z',
        metadata: {
          signal_type: 'research_publication',
          citations: 45,
        },
      },
    ],
    evidenceSnapshot: {
      query: 'signal_type:research_publication AND keywords:AI safety',
      conditions: [
        {
          id: 'cond-3',
          field: 'signal_type',
          operator: 'equals',
          value: 'research_publication',
        },
        {
          id: 'cond-4',
          field: 'keywords',
          operator: 'contains',
          value: 'AI safety',
          logic: 'AND',
        },
      ],
      totalMatches: 2,
      sampleDocuments: [
        {
          id: 'doc-4',
          title: 'Constitutional AI: Harmlessness from AI Feedback',
          source: 'arXiv',
          url: 'https://arxiv.org/abs/2212.xxxxx',
          excerpt: 'We introduce a method for training AI systems...',
          matchScore: 0.91,
          publishedAt: '2024-11-19T18:00:00Z',
          metadata: {},
        },
      ],
      capturedAt: '2024-11-19T23:00:00Z',
    },
    actionsPerformed: [
      {
        id: 'action-8',
        action: 'delivered',
        channel: 'in-app',
        timestamp: '2024-11-19T23:00:05Z',
        details: 'Digest notification delivered',
        success: true,
      },
      {
        id: 'action-9',
        action: 'delivered',
        channel: 'email',
        timestamp: '2024-11-19T23:00:10Z',
        details: 'Daily digest email sent',
        success: true,
      },
    ],
    deliveryStatus: [
      {
        channel: 'in-app',
        status: 'delivered',
        timestamp: '2024-11-19T23:00:05Z',
        retryCount: 0,
      },
      {
        channel: 'email',
        status: 'delivered',
        timestamp: '2024-11-19T23:00:10Z',
        retryCount: 0,
      },
    ],
  },
];

export const mockAlertMetrics: AlertMetrics = {
  totalAlerts: 6,
  activeAlerts: 5,
  mutedAlerts: 1,
  triggersLast24h: 12,
  triggersLast7d: 89,
  avgResponseTime: 2.3,
  successRate: 98.5,
  signalToNoiseRatio: 0.82,
};

export const mockWatchedTechnologies: WatchedTechnology[] = [
  {
    id: 'watch-1',
    technologyId: 'tech-1',
    name: 'Quantum Computing',
    domain: 'Computing & IT',
    addedAt: '2024-10-01T10:00:00Z',
    lastUpdate: '2024-11-20T08:45:00Z',
    updateCount: 24,
    alertsEnabled: true,
    recentChanges: [
      {
        id: 'update-1',
        type: 'news',
        title: 'IBM Announces 1000-Qubit Quantum Processor',
        description: 'Major breakthrough in quantum computing hardware',
        timestamp: '2024-11-20T08:45:00Z',
        severity: 'critical',
        source: 'IBM Research',
        url: 'https://research.ibm.com/quantum-1000',
      },
      {
        id: 'update-2',
        type: 'patent',
        title: 'Error Correction Method for Quantum Systems',
        description: 'New patent filed for improved quantum error correction',
        timestamp: '2024-11-18T14:20:00Z',
        severity: 'medium',
        source: 'USPTO',
      },
      {
        id: 'update-3',
        type: 'funding',
        title: 'IonQ Raises $100M in Strategic Funding',
        description: 'Quantum computing company secures major investment',
        timestamp: '2024-11-15T09:30:00Z',
        severity: 'high',
        source: 'TechCrunch',
      },
    ],
  },
  {
    id: 'watch-2',
    technologyId: 'tech-2',
    name: 'Solid-State Batteries',
    domain: 'Energy Storage',
    addedAt: '2024-09-15T14:30:00Z',
    lastUpdate: '2024-11-18T10:20:00Z',
    updateCount: 18,
    alertsEnabled: true,
    recentChanges: [
      {
        id: 'update-4',
        type: 'funding',
        title: 'QuantumScape Secures $150M Series E',
        description: 'Major funding round for solid-state battery manufacturer',
        timestamp: '2024-11-18T10:20:00Z',
        severity: 'medium',
        source: 'TechCrunch',
      },
      {
        id: 'update-5',
        type: 'publication',
        title: 'Advances in Lithium Metal Anodes',
        description: 'Research breakthrough in battery energy density',
        timestamp: '2024-11-12T16:45:00Z',
        severity: 'medium',
        source: 'Nature Energy',
      },
    ],
  },
  {
    id: 'watch-3',
    technologyId: 'tech-3',
    name: 'CRISPR Gene Editing',
    domain: 'Biotechnology',
    addedAt: '2024-08-10T08:30:00Z',
    lastUpdate: '2024-11-11T09:00:00Z',
    updateCount: 15,
    alertsEnabled: false,
    recentChanges: [
      {
        id: 'update-6',
        type: 'patent',
        title: 'CRISPR-Cas9 Delivery System Patent',
        description: 'New patent for improved gene editing delivery mechanism',
        timestamp: '2024-11-11T09:00:00Z',
        severity: 'high',
        source: 'USPTO',
      },
    ],
  },
  {
    id: 'watch-4',
    technologyId: 'tech-4',
    name: 'Nuclear Fusion',
    domain: 'Energy Generation',
    addedAt: '2024-10-05T11:45:00Z',
    lastUpdate: '2024-11-20T06:00:00Z',
    updateCount: 31,
    alertsEnabled: true,
    recentChanges: [
      {
        id: 'update-7',
        type: 'signal',
        title: 'NIF Achieves Net Energy Gain',
        description: 'Historic milestone in fusion energy research',
        timestamp: '2024-11-20T06:00:00Z',
        severity: 'critical',
        source: 'Nature',
        url: 'https://nature.com/fusion-net-gain',
      },
      {
        id: 'update-8',
        type: 'funding',
        title: 'Commonwealth Fusion Systems Raises $1.8B',
        description: 'Largest private investment in fusion energy',
        timestamp: '2024-11-10T13:15:00Z',
        severity: 'high',
        source: 'Bloomberg',
      },
    ],
  },
];

export const mockAlertTemplates: AlertTemplate[] = [
  {
    id: 'template-1',
    name: 'Breakthrough Detection',
    description: 'Monitor high-impact breakthroughs in a specific technology',
    category: 'technology',
    triggerType: 'query',
    defaultConditions: [
      {
        id: 'temp-cond-1',
        field: 'signal_strength',
        operator: 'greater_than',
        value: 0.8,
      },
      {
        id: 'temp-cond-2',
        field: 'trl',
        operator: 'greater_than',
        value: 7,
        logic: 'AND',
      },
    ],
    recommendedFrequency: 'real-time',
    icon: '🚀',
  },
  {
    id: 'template-2',
    name: 'Research Publication Tracker',
    description: 'Track new research papers in specific domains',
    category: 'technology',
    triggerType: 'signal',
    defaultConditions: [
      {
        id: 'temp-cond-3',
        field: 'signal_type',
        operator: 'equals',
        value: 'research_publication',
      },
    ],
    recommendedFrequency: 'daily',
    icon: '📄',
  },
  {
    id: 'template-3',
    name: 'Funding & Investment Alert',
    description: 'Monitor major funding rounds and investments',
    category: 'market',
    triggerType: 'threshold',
    defaultConditions: [
      {
        id: 'temp-cond-4',
        field: 'signal_type',
        operator: 'equals',
        value: 'funding',
      },
      {
        id: 'temp-cond-5',
        field: 'funding_amount',
        operator: 'greater_than',
        value: 5000000,
        logic: 'AND',
      },
    ],
    recommendedFrequency: 'real-time',
    icon: '💰',
  },
  {
    id: 'template-4',
    name: 'Patent Filing Monitor',
    description: 'Track patent applications in technology areas',
    category: 'technology',
    triggerType: 'entity',
    defaultConditions: [
      {
        id: 'temp-cond-6',
        field: 'entity_type',
        operator: 'equals',
        value: 'patent',
      },
    ],
    recommendedFrequency: 'weekly',
    icon: '⚖️',
  },
  {
    id: 'template-5',
    name: 'Competitor Activity Tracker',
    description: 'Monitor specific organizations and competitors',
    category: 'competitor',
    triggerType: 'entity',
    defaultConditions: [
      {
        id: 'temp-cond-7',
        field: 'entity_type',
        operator: 'equals',
        value: 'organization',
      },
    ],
    recommendedFrequency: 'daily',
    icon: '🎯',
  },
  {
    id: 'template-6',
    name: 'Market Opportunity Alert',
    description: 'Detect emerging market opportunities',
    category: 'market',
    triggerType: 'query',
    defaultConditions: [
      {
        id: 'temp-cond-8',
        field: 'market_growth',
        operator: 'greater_than',
        value: 20,
      },
    ],
    recommendedFrequency: 'weekly',
    icon: '📈',
  },
];

export const mockNotificationPreferences: NotificationPreference = {
  userId: 'user-1',
  enableInApp: true,
  enableEmail: true,
  enableSlack: false,
  quietHours: {
    enabled: true,
    start: '22:00',
    end: '08:00',
    timezone: 'Asia/Kolkata',
  },
  severityFilters: {
    critical: true,
    high: true,
    medium: true,
    low: false,
  },
  digestMode: {
    enabled: true,
    frequency: 'daily',
    time: '09:00',
  },
};

export const mockAlertPreviewResult: AlertPreviewResult = {
  estimatedMatches: 47,
  sampleDocuments: [
    {
      id: 'preview-1',
      title: 'Google Unveils Willow Quantum Chip',
      source: 'Google AI Blog',
      url: 'https://blog.google/quantum-willow',
      excerpt: 'Google has announced Willow, a new quantum chip that demonstrates exponential error reduction...',
      matchScore: 0.94,
      publishedAt: '2024-11-15T10:00:00Z',
      metadata: {
        domain: 'Quantum Computing',
        trl: 7,
      },
    },
    {
      id: 'preview-2',
      title: 'IQM Quantum Computers Achieves 20-Qubit Coherence',
      source: 'IQM Press Release',
      url: 'https://iqm.com/press/20-qubit',
      excerpt: 'IQM announces breakthrough in maintaining quantum coherence across 20 qubits simultaneously...',
      matchScore: 0.89,
      publishedAt: '2024-11-12T14:30:00Z',
      metadata: {
        domain: 'Quantum Computing',
        trl: 6,
      },
    },
    {
      id: 'preview-3',
      title: 'Quantum Algorithm Breakthrough for Drug Discovery',
      source: 'Nature Computational Science',
      url: 'https://nature.com/quantum-drug',
      excerpt: 'Researchers develop quantum algorithm that accelerates molecular simulation for pharmaceutical applications...',
      matchScore: 0.86,
      publishedAt: '2024-11-08T09:15:00Z',
      metadata: {
        domain: 'Quantum Computing',
        trl: 5,
      },
    },
  ],
  historicalTriggers: [
    { date: '2024-11-20', count: 2 },
    { date: '2024-11-19', count: 1 },
    { date: '2024-11-18', count: 3 },
    { date: '2024-11-17', count: 0 },
    { date: '2024-11-16', count: 2 },
    { date: '2024-11-15', count: 4 },
    { date: '2024-11-14', count: 1 },
  ],
  noiseLevel: 'low',
  recommendations: [
    'Consider increasing the TRL threshold to 8 to reduce false positives',
    'Add organization filter to focus on specific research institutions',
    'Enable deduplication with 60-minute window to prevent duplicate alerts',
    'Current settings should generate approximately 2-3 alerts per day',
  ],
};