// Mock Data for Technology Detail View

import {
  TechnologyMetadata,
  TRLHistoryEntry,
  TimelineEvent,
  TechSignals,
  Source,
  KnowledgeGraph,
  SCurveData,
  HypeCurveData,
  ForecastModel,
  Comment,
  TechDetailResponse,
  TechSignalsResponse,
  TechSourcesResponse,
  KnowledgeGraphResponse,
  ForecastResponse,
} from "@/types/tech-detail";

// Mock Technology Metadata
export const mockTechMetadata: TechnologyMetadata = {
  id: "tech-001",
  name: "Solid-State Battery Technology",
  canonicalSummary: "Next-generation battery technology using solid electrolytes instead of liquid, offering higher energy density, improved safety, and longer lifespan for electric vehicles and energy storage.",
  domains: ["Clean Energy", "Advanced Materials"],
  currentTRL: 6,
  confidence: "high",
  lastUpdated: "2024-11-15T10:30:00Z",
  isWatched: false,
  relatedTechCount: 23,
  sourceCount: 487,
};

// Mock TRL History
export const mockTRLHistory: TRLHistoryEntry[] = [
  {
    trl: 3,
    date: "2018-03-15",
    confidence: "high",
    evidenceIds: ["src-001", "src-002", "src-005"],
    reasoning: "Laboratory proof of concept demonstrated by multiple research institutions",
    keyMilestones: [
      "Toyota Research Institute demonstrated solid electrolyte stability",
      "Published in Nature Energy with reproducible results"
    ],
  },
  {
    trl: 4,
    date: "2019-09-20",
    confidence: "high",
    evidenceIds: ["src-015", "src-018", "src-022"],
    reasoning: "Component validation in laboratory environment with multiple cycles",
    keyMilestones: [
      "QuantumScape achieved 1000+ charge cycles",
      "Stanford team validated lithium metal anode compatibility"
    ],
  },
  {
    trl: 5,
    date: "2021-06-10",
    confidence: "high",
    evidenceIds: ["src-045", "src-048", "src-052", "src-055"],
    reasoning: "Component validation in relevant environment with automotive partners",
    keyMilestones: [
      "BMW partnership for prototype testing",
      "Real-world temperature and vibration testing completed",
      "Manufacturing process feasibility confirmed"
    ],
  },
  {
    trl: 6,
    date: "2023-11-28",
    confidence: "medium",
    evidenceIds: ["src-112", "src-115", "src-120", "src-125", "src-130"],
    reasoning: "System/subsystem prototype demonstration in operational environment",
    keyMilestones: [
      "Toyota unveiled prototype EV with solid-state battery",
      "Nissan announced pilot production line",
      "Samsung SDI completed prototype testing with major OEM",
      "Production cost analysis shows path to parity with Li-ion by 2027"
    ],
  },
];

// Mock Timeline Events
export const mockTimelineEvents: TimelineEvent[] = [
  {
    id: "evt-001",
    type: "paper",
    title: "Stable Lithium-Ion Conduction in Sulfide Solid Electrolytes",
    date: "2018-01-15",
    description: "Breakthrough research on sulfide-based solid electrolytes showing high ionic conductivity at room temperature",
    sourceUrl: "https://doi.org/10.1038/nature12345",
    confidence: "high",
    impactScore: 85,
    organization: "MIT",
    country: "USA",
    tags: ["materials", "electrolyte", "sulfide"],
  },
  {
    id: "evt-002",
    type: "patent",
    title: "Solid Electrolyte Interface Formation Method",
    date: "2018-06-22",
    description: "Patent for novel manufacturing process to create stable solid-electrolyte interfaces",
    confidence: "high",
    impactScore: 72,
    organization: "Toyota Motor Corporation",
    country: "Japan",
    tags: ["manufacturing", "interface", "process"],
  },
  {
    id: "evt-003",
    type: "startup",
    title: "QuantumScape Founded",
    date: "2018-09-10",
    description: "Solid-state battery startup founded with backing from VW and Bill Gates",
    confidence: "high",
    impactScore: 90,
    organization: "QuantumScape",
    country: "USA",
    tags: ["startup", "funding", "commercialization"],
  },
  {
    id: "evt-004",
    type: "funding",
    title: "Series C - $200M Round",
    date: "2019-04-18",
    description: "Major funding round led by Volkswagen Group for solid-state battery development",
    confidence: "high",
    impactScore: 88,
    organization: "QuantumScape",
    country: "USA",
    tags: ["funding", "investment", "volkswagen"],
  },
  {
    id: "evt-005",
    type: "demo",
    title: "1000-Cycle Demonstration",
    date: "2020-12-08",
    description: "Public demonstration of solid-state cell achieving 1000+ charge cycles with minimal degradation",
    sourceUrl: "https://quantumscape.com/demo-2020",
    confidence: "high",
    impactScore: 95,
    organization: "QuantumScape",
    country: "USA",
    tags: ["demo", "performance", "cycles"],
  },
  {
    id: "evt-006",
    type: "paper",
    title: "Scalable Manufacturing of All-Solid-State Batteries",
    date: "2021-03-12",
    description: "Research paper outlining scalable manufacturing processes for commercial production",
    sourceUrl: "https://doi.org/10.1126/science.12345",
    confidence: "high",
    impactScore: 78,
    organization: "Stanford University",
    country: "USA",
    tags: ["manufacturing", "scalability", "production"],
  },
  {
    id: "evt-007",
    type: "funding",
    title: "BMW Partnership - $150M",
    date: "2021-08-25",
    description: "Strategic partnership and investment for automotive integration",
    confidence: "high",
    impactScore: 82,
    organization: "BMW Group",
    country: "Germany",
    tags: ["partnership", "automotive", "integration"],
  },
  {
    id: "evt-008",
    type: "patent",
    title: "High-Rate Charging Solid-State Cell Architecture",
    date: "2022-02-14",
    description: "Patent for cell design enabling 15-minute fast charging capability",
    confidence: "medium",
    impactScore: 85,
    organization: "Samsung SDI",
    country: "South Korea",
    tags: ["fast-charging", "architecture", "design"],
  },
  {
    id: "evt-009",
    type: "demo",
    title: "Toyota Prototype EV Reveal",
    date: "2023-06-20",
    description: "First prototype electric vehicle equipped with solid-state battery demonstrated to media",
    sourceUrl: "https://toyota.com/solid-state-ev",
    confidence: "high",
    impactScore: 92,
    organization: "Toyota Motor Corporation",
    country: "Japan",
    tags: ["prototype", "automotive", "demonstration"],
  },
  {
    id: "evt-010",
    type: "news",
    title: "Nissan Announces Pilot Production Facility",
    date: "2024-01-15",
    description: "Nissan unveils pilot production line for solid-state batteries with 2027 commercial launch target",
    sourceUrl: "https://news.nissan.com/solid-state-2024",
    confidence: "high",
    impactScore: 88,
    organization: "Nissan Motor Co.",
    country: "Japan",
    tags: ["production", "manufacturing", "commercialization"],
  },
  {
    id: "evt-011",
    type: "funding",
    title: "EU Invests €500M in Solid-State Research",
    date: "2024-03-10",
    description: "European Union launches major funding initiative for solid-state battery technology",
    confidence: "high",
    impactScore: 75,
    organization: "European Commission",
    country: "EU",
    tags: ["government", "funding", "policy"],
  },
  {
    id: "evt-012",
    type: "paper",
    title: "Cost Analysis: Path to Commercial Viability",
    date: "2024-09-05",
    description: "Comprehensive techno-economic analysis showing cost parity with Li-ion by 2027",
    sourceUrl: "https://doi.org/10.1016/nature.2024.12345",
    confidence: "medium",
    impactScore: 80,
    organization: "McKinsey & Company",
    country: "USA",
    tags: ["economics", "cost", "analysis"],
  },
];

// Mock Tech Signals
export const mockTechSignals: TechSignals = {
  patents: {
    timeseries: [
      { date: "2018-01", value: 45, confidence: "high" },
      { date: "2018-07", value: 52, confidence: "high" },
      { date: "2019-01", value: 68, confidence: "high" },
      { date: "2019-07", value: 89, confidence: "high" },
      { date: "2020-01", value: 112, confidence: "high" },
      { date: "2020-07", value: 145, confidence: "high" },
      { date: "2021-01", value: 178, confidence: "high" },
      { date: "2021-07", value: 215, confidence: "high" },
      { date: "2022-01", value: 268, confidence: "high" },
      { date: "2022-07", value: 312, confidence: "high" },
      { date: "2023-01", value: 378, confidence: "high" },
      { date: "2023-07", value: 435, confidence: "high" },
      { date: "2024-01", value: 487, confidence: "medium" },
      { date: "2024-07", value: 542, confidence: "medium" },
    ],
    total: 542,
    growth: 11.3,
  },
  papers: {
    timeseries: [
      { date: "2018-01", value: 23 },
      { date: "2018-07", value: 31 },
      { date: "2019-01", value: 45 },
      { date: "2019-07", value: 67 },
      { date: "2020-01", value: 89 },
      { date: "2020-07", value: 112 },
      { date: "2021-01", value: 145 },
      { date: "2021-07", value: 178 },
      { date: "2022-01", value: 215 },
      { date: "2022-07", value: 256 },
      { date: "2023-01", value: 302 },
      { date: "2023-07", value: 348 },
      { date: "2024-01", value: 398 },
      { date: "2024-07", value: 445 },
    ],
    total: 445,
    citations: 12456,
  },
  funding: {
    timeseries: [
      { date: "2018-Q1", value: 25 },
      { date: "2018-Q3", value: 42 },
      { date: "2019-Q1", value: 78 },
      { date: "2019-Q3", value: 125 },
      { date: "2020-Q1", value: 210 },
      { date: "2020-Q3", value: 345 },
      { date: "2021-Q1", value: 520 },
      { date: "2021-Q3", value: 680 },
      { date: "2022-Q1", value: 890 },
      { date: "2022-Q3", value: 1150 },
      { date: "2023-Q1", value: 1420 },
      { date: "2023-Q3", value: 1680 },
      { date: "2024-Q1", value: 1950 },
      { date: "2024-Q3", value: 2180 },
    ],
    totalAmount: 2180,
    rounds: 48,
  },
  googleTrends: {
    timeseries: [
      { date: "2018-01", value: 12 },
      { date: "2018-07", value: 15 },
      { date: "2019-01", value: 22 },
      { date: "2019-07", value: 28 },
      { date: "2020-01", value: 38 },
      { date: "2020-07", value: 52 },
      { date: "2021-01", value: 61 },
      { date: "2021-07", value: 68 },
      { date: "2022-01", value: 74 },
      { date: "2022-07", value: 79 },
      { date: "2023-01", value: 85 },
      { date: "2023-07", value: 88 },
      { date: "2024-01", value: 92 },
      { date: "2024-07", value: 95 },
    ],
    currentInterest: 95,
  },
  startups: {
    timeseries: [
      { date: "2018", value: 3 },
      { date: "2019", value: 7 },
      { date: "2020", value: 12 },
      { date: "2021", value: 18 },
      { date: "2022", value: 25 },
      { date: "2023", value: 31 },
      { date: "2024", value: 35 },
    ],
    total: 35,
    activeCount: 28,
  },
};

// Mock Sources
export const mockSources: Source[] = [
  {
    id: "src-001",
    type: "paper",
    title: "Stable Lithium-Ion Conduction in Sulfide Solid Electrolytes",
    date: "2018-01-15",
    authors: ["Dr. Jane Chen", "Prof. Michael Rodriguez", "Dr. Sarah Kim"],
    organization: "MIT",
    url: "https://doi.org/10.1038/nature12345",
    abstract: "We report stable lithium-ion conduction in sulfide-based solid electrolytes at room temperature, achieving ionic conductivity of 10 mS/cm...",
    confidence: "high",
    citationCount: 1247,
    impactScore: 95,
    tags: ["materials", "electrolyte", "sulfide", "ionic-conductivity"],
    rawDocumentUrl: "https://storage.intelforge.com/papers/src-001.pdf",
    usedInForecast: true,
    forecastWeight: 0.85,
  },
  {
    id: "src-015",
    type: "patent",
    title: "Solid Electrolyte Interface Formation Method",
    date: "2018-06-22",
    authors: ["Hiroshi Tanaka", "Yuki Yamamoto"],
    organization: "Toyota Motor Corporation",
    url: "https://patents.google.com/patent/US123456789",
    abstract: "Method and apparatus for forming stable solid-electrolyte interfaces in lithium metal batteries using controlled pressure and temperature...",
    confidence: "high",
    citationCount: 89,
    impactScore: 82,
    tags: ["manufacturing", "interface", "process", "lithium-metal"],
    rawDocumentUrl: "https://storage.intelforge.com/patents/src-015.pdf",
    usedInForecast: true,
    forecastWeight: 0.72,
  },
  {
    id: "src-045",
    type: "demo",
    title: "1000-Cycle Solid-State Cell Demonstration",
    date: "2020-12-08",
    organization: "QuantumScape",
    url: "https://quantumscape.com/demo-2020",
    abstract: "Public demonstration of single-layer solid-state lithium-metal cell achieving 1000+ charge cycles at 1C rate with <10% capacity fade...",
    confidence: "high",
    impactScore: 98,
    tags: ["demo", "performance", "cycles", "degradation"],
    rawDocumentUrl: "https://storage.intelforge.com/demos/src-045.mp4",
    usedInForecast: true,
    forecastWeight: 0.92,
  },
  {
    id: "src-112",
    type: "news",
    title: "Toyota Unveils Solid-State Battery Prototype Vehicle",
    date: "2023-06-20",
    organization: "Toyota Motor Corporation",
    url: "https://toyota.com/news/solid-state-ev-2023",
    abstract: "Toyota reveals first prototype electric vehicle equipped with solid-state battery technology, demonstrating 500km range and 15-minute fast charging...",
    confidence: "high",
    impactScore: 94,
    tags: ["prototype", "automotive", "demonstration", "commercialization"],
    usedInForecast: true,
    forecastWeight: 0.88,
  },
  {
    id: "src-115",
    type: "paper",
    title: "Scalable Manufacturing of All-Solid-State Batteries: Techno-Economic Analysis",
    date: "2024-09-05",
    authors: ["Dr. Emily Watson", "Dr. James Anderson"],
    organization: "McKinsey & Company",
    url: "https://doi.org/10.1016/nature.2024.12345",
    abstract: "Comprehensive analysis of manufacturing costs and scaling pathways for solid-state batteries, projecting cost parity with lithium-ion by 2027...",
    confidence: "medium",
    citationCount: 234,
    impactScore: 86,
    tags: ["economics", "cost", "analysis", "manufacturing", "scaling"],
    rawDocumentUrl: "https://storage.intelforge.com/papers/src-115.pdf",
    usedInForecast: true,
    forecastWeight: 0.78,
  },
  {
    id: "src-120",
    type: "funding",
    title: "BMW Strategic Investment - $150M",
    date: "2021-08-25",
    organization: "BMW Group",
    abstract: "BMW announces strategic partnership and $150M investment in solid-state battery technology for next-generation electric vehicles...",
    confidence: "high",
    impactScore: 82,
    tags: ["funding", "partnership", "automotive", "investment"],
    usedInForecast: true,
    forecastWeight: 0.65,
  },
];

// Mock Knowledge Graph
export const mockKnowledgeGraph: KnowledgeGraph = {
  nodes: [
    {
      id: "tech-001",
      type: "technology",
      label: "Solid-State Battery",
      description: "Central technology node",
      size: 100,
      color: "#3b82f6",
    },
    {
      id: "company-001",
      type: "company",
      label: "QuantumScape",
      description: "Leading solid-state battery startup",
      size: 85,
      color: "#10b981",
      metadata: { founded: 2010, employees: 850 },
    },
    {
      id: "company-002",
      type: "company",
      label: "Toyota",
      description: "Major automotive OEM investor",
      size: 90,
      color: "#10b981",
    },
    {
      id: "company-003",
      type: "company",
      label: "Samsung SDI",
      description: "Battery manufacturer",
      size: 75,
      color: "#10b981",
    },
    {
      id: "company-004",
      type: "company",
      label: "BMW",
      description: "Automotive partner",
      size: 70,
      color: "#10b981",
    },
    {
      id: "inst-001",
      type: "institution",
      label: "MIT",
      description: "Research institution",
      size: 65,
      color: "#8b5cf6",
    },
    {
      id: "inst-002",
      type: "institution",
      label: "Stanford",
      description: "Research institution",
      size: 60,
      color: "#8b5cf6",
    },
    {
      id: "author-001",
      type: "author",
      label: "Dr. Jane Chen",
      description: "Lead researcher at MIT",
      size: 45,
      color: "#f59e0b",
    },
    {
      id: "author-002",
      type: "author",
      label: "Prof. Michael Rodriguez",
      description: "Stanford professor",
      size: 42,
      color: "#f59e0b",
    },
    {
      id: "funder-001",
      type: "funder",
      label: "Volkswagen Group",
      description: "Major investor",
      size: 80,
      color: "#ef4444",
    },
    {
      id: "tech-002",
      type: "technology",
      label: "Lithium Metal Anode",
      description: "Related technology",
      size: 55,
      color: "#3b82f6",
    },
    {
      id: "tech-003",
      type: "technology",
      label: "Sulfide Electrolyte",
      description: "Related technology",
      size: 50,
      color: "#3b82f6",
    },
    {
      id: "tech-004",
      type: "technology",
      label: "Fast Charging",
      description: "Related technology",
      size: 48,
      color: "#3b82f6",
    },
  ],
  edges: [
    { source: "company-001", target: "tech-001", type: "develops", weight: 0.95 },
    { source: "company-002", target: "tech-001", type: "develops", weight: 0.90 },
    { source: "company-003", target: "tech-001", type: "develops", weight: 0.85 },
    { source: "funder-001", target: "company-001", type: "funds", weight: 0.92 },
    { source: "company-004", target: "company-001", type: "collaborates", weight: 0.78 },
    { source: "inst-001", target: "tech-001", type: "develops", weight: 0.88 },
    { source: "inst-002", target: "tech-001", type: "develops", weight: 0.82 },
    { source: "author-001", target: "inst-001", type: "collaborates", weight: 0.95 },
    { source: "author-002", target: "inst-002", type: "collaborates", weight: 0.92 },
    { source: "tech-001", target: "tech-002", type: "related", weight: 0.88 },
    { source: "tech-001", target: "tech-003", type: "related", weight: 0.85 },
    { source: "tech-001", target: "tech-004", type: "related", weight: 0.72 },
    { source: "author-001", target: "author-002", type: "collaborates", weight: 0.65 },
    { source: "company-002", target: "company-004", type: "collaborates", weight: 0.58 },
  ],
  centerNodeId: "tech-001",
};

// Mock S-Curve Data
export const mockSCurveData: SCurveData = {
  observed: [
    { date: "2018", adoption: 2, confidence: "high" },
    { date: "2019", adoption: 5, confidence: "high" },
    { date: "2020", adoption: 10, confidence: "high" },
    { date: "2021", adoption: 18, confidence: "high" },
    { date: "2022", adoption: 28, confidence: "high" },
    { date: "2023", adoption: 42, confidence: "medium" },
    { date: "2024", adoption: 58, confidence: "medium" },
  ],
  fitted: [
    { date: "2018", adoption: 3 },
    { date: "2019", adoption: 6 },
    { date: "2020", adoption: 11 },
    { date: "2021", adoption: 19 },
    { date: "2022", adoption: 30 },
    { date: "2023", adoption: 43 },
    { date: "2024", adoption: 57 },
    { date: "2025", adoption: 70, upperBound: 78, lowerBound: 62 },
    { date: "2026", adoption: 80, upperBound: 88, lowerBound: 72 },
    { date: "2027", adoption: 87, upperBound: 93, lowerBound: 81 },
    { date: "2028", adoption: 92, upperBound: 96, lowerBound: 88 },
    { date: "2029", adoption: 95, upperBound: 98, lowerBound: 92 },
    { date: "2030", adoption: 97, upperBound: 99, lowerBound: 95 },
  ],
  inflectionPoint: {
    date: "2024-06",
    adoption: 58,
  },
  maturityPhase: "growth",
};

// Mock Hype Curve Data
export const mockHypeCurveData: HypeCurveData = {
  phases: [
    { phase: "trigger", date: "2018-Q1", intensity: 15, confidence: "high" },
    { phase: "peak", date: "2020-Q4", intensity: 92, confidence: "high" },
    { phase: "trough", date: "2022-Q2", intensity: 38, confidence: "medium" },
    { phase: "slope", date: "2024-Q3", intensity: 68, confidence: "medium" },
  ],
  currentPhase: "slope",
  peakDate: "2020-12",
  plateauEstimate: "2027-Q2",
};

// Mock Forecast Model
export const mockForecastModel: ForecastModel = {
  id: "forecast-001",
  name: "ML Ensemble Forecast",
  version: "2.1.4",
  lastRun: "2024-11-15T10:30:00Z",
  scenarios: [
    {
      scenario: "optimistic",
      predictions: [
        { date: "2025", trl: 7, marketSize: 2.5, adoptionRate: 12, confidence: "medium" },
        { date: "2026", trl: 8, marketSize: 8.5, adoptionRate: 28, confidence: "medium" },
        { date: "2027", trl: 8, marketSize: 18.5, adoptionRate: 45, confidence: "low" },
        { date: "2028", trl: 9, marketSize: 35.0, adoptionRate: 62, confidence: "low" },
      ],
      keyAssumptions: [
        "Manufacturing costs reach parity with Li-ion by 2026",
        "Major OEM adoption accelerates post-2025",
        "No major safety incidents or regulatory setbacks",
        "Supply chain scales successfully"
      ],
      uncertaintyBands: {
        upper: [15, 35, 55, 75],
        lower: [8, 20, 35, 50],
      },
    },
    {
      scenario: "baseline",
      predictions: [
        { date: "2025", trl: 7, marketSize: 1.8, adoptionRate: 8, confidence: "high" },
        { date: "2026", trl: 7, marketSize: 5.2, adoptionRate: 18, confidence: "medium" },
        { date: "2027", trl: 8, marketSize: 12.5, adoptionRate: 32, confidence: "medium" },
        { date: "2028", trl: 8, marketSize: 22.0, adoptionRate: 48, confidence: "low" },
      ],
      keyAssumptions: [
        "Manufacturing costs reach parity with Li-ion by 2027",
        "Gradual OEM adoption following successful pilots",
        "Standard regulatory approval timelines",
        "Moderate supply chain scaling"
      ],
      uncertaintyBands: {
        upper: [10, 22, 40, 58],
        lower: [6, 14, 24, 38],
      },
    },
    {
      scenario: "pessimistic",
      predictions: [
        { date: "2025", trl: 6, marketSize: 0.8, adoptionRate: 4, confidence: "high" },
        { date: "2026", trl: 7, marketSize: 2.5, adoptionRate: 10, confidence: "medium" },
        { date: "2027", trl: 7, marketSize: 6.5, adoptionRate: 18, confidence: "low" },
        { date: "2028", trl: 7, marketSize: 12.0, adoptionRate: 28, confidence: "low" },
      ],
      keyAssumptions: [
        "Manufacturing costs remain 30% above Li-ion through 2028",
        "OEM adoption delayed due to technical challenges",
        "Extended regulatory approval processes",
        "Supply chain bottlenecks"
      ],
      uncertaintyBands: {
        upper: [6, 14, 25, 38],
        lower: [2, 6, 12, 18],
      },
    },
  ],
  inputSources: [
    { sourceId: "src-001", weight: 0.85, contribution: "Fundamental materials breakthrough" },
    { sourceId: "src-045", weight: 0.92, contribution: "Cycle life validation" },
    { sourceId: "src-112", weight: 0.88, contribution: "Prototype demonstration" },
    { sourceId: "src-115", weight: 0.78, contribution: "Economic feasibility" },
    { sourceId: "src-015", weight: 0.72, contribution: "Manufacturing process" },
  ],
  accuracy: {
    score: 78,
    historicalError: 12.5,
    confidenceInterval: [65, 88],
  },
  explanation: {
    topDrivers: [
      {
        factor: "Manufacturing Scale-Up",
        impact: 85,
        reasoning: "Critical path to cost parity; pilot lines operational but full-scale production timeline uncertain",
      },
      {
        factor: "Energy Density Achievement",
        impact: 72,
        reasoning: "Demonstrated 2x improvement over Li-ion in prototypes; key differentiator for market adoption",
      },
      {
        factor: "Safety Validation",
        impact: 68,
        reasoning: "Solid electrolyte eliminates thermal runaway risk; regulatory approval process ongoing",
      },
      {
        factor: "OEM Partnership Momentum",
        impact: 65,
        reasoning: "Toyota, BMW, Nissan committed; broader adoption depends on successful launches",
      },
      {
        factor: "Cost Trajectory",
        impact: -45,
        reasoning: "Current costs 3-4x higher than Li-ion; scaling required to reach parity by 2027-2028",
      },
    ],
    methodology: "Ensemble model combining S-curve fitting, patent velocity analysis, funding momentum, and expert surveys. Weighted by source confidence and recency.",
    limitations: [
      "Limited real-world performance data beyond prototypes",
      "Manufacturing scale-up timelines highly uncertain",
      "Dependent on external factors (raw material supply, regulatory changes)",
      "Market adoption rates based on historical analogies (Li-ion, LED lighting)"
    ],
  },
};

// Mock Comments
export const mockComments: Comment[] = [
  {
    id: "comment-001",
    userId: "user-123",
    userName: "Alex Kumar",
    userAvatar: "AK",
    content: "The QuantumScape demo was a major turning point. Their single-layer cell achieving 1000+ cycles changed the industry narrative from 'if' to 'when'.",
    createdAt: "2024-10-15T14:23:00Z",
    isPinned: true,
    attachedSourceIds: ["src-045"],
    replies: [
      {
        id: "comment-002",
        userId: "user-456",
        userName: "Sarah Chen",
        userAvatar: "SC",
        content: "Agreed, but we should be cautious about scaling multi-layer cells. The single-layer demo doesn't fully address manufacturing complexity.",
        createdAt: "2024-10-16T09:15:00Z",
        isPinned: false,
      },
    ],
  },
  {
    id: "comment-003",
    userId: "user-789",
    userName: "Marcus Johnson",
    userAvatar: "MJ",
    content: "Cost analysis from McKinsey is crucial. The 2027 cost parity projection aligns with our internal models, assuming no major supply chain disruptions.",
    createdAt: "2024-11-01T11:30:00Z",
    isPinned: false,
    attachedSourceIds: ["src-115"],
  },
];

// API Response Mock Functions
export const getMockTechDetail = (id: string): TechDetailResponse => ({
  metadata: mockTechMetadata,
  trlHistory: mockTRLHistory,
});

export const getMockTechSignals = (id: string): TechSignalsResponse => ({
  techId: id,
  signals: mockTechSignals,
  lastUpdated: "2024-11-15T10:30:00Z",
});

export const getMockTechSources = (
  id: string,
  page: number = 1,
  pageSize: number = 20
): TechSourcesResponse => ({
  techId: id,
  sources: mockSources,
  total: 487,
  page,
  pageSize,
});

export const getMockKnowledgeGraph = (id: string): KnowledgeGraphResponse => ({
  techId: id,
  graph: mockKnowledgeGraph,
  generatedAt: "2024-11-15T10:30:00Z",
});

export const getMockForecast = (id: string): ForecastResponse => ({
  techId: id,
  model: mockForecastModel,
  sCurve: mockSCurveData,
  hypeCurve: mockHypeCurveData,
  generatedAt: "2024-11-15T10:30:00Z",
});